### PR TITLE
FE1 - Side bar menu implementation

### LINKED ISSUE #4: FE1 - Implement sidebar menu
Implementation of the sidebar menu based on the redesigned layout: 

- [x] Implement Sidebar component in the LiquityFrontend
- [x] Adapt frontend layout structure to have a sidebar with absolute position
- [x] Create and implement Nav with Links, and icons components as children of Sidebar
- [x] Implement a hamburger menu for mobile version (responsive)

Screenshot from 2022-03-22 22-48-30

### PR DESCRIPTION
**Pull request by evandrosaturnino**
Implementation of the sidebar menu based on the redesigned layout

[X] - Adapted frontend layout structure to have a sidebar with absolute position
[X] - Implemented a Sidebar with a navigation menu linking to different paths within the application
[X] - Implemented a hamburger menu for the sidebar menu in the mobile screens version (responsive)

closes #4

### CODE REVIEW

**Comment by benlongstaff** [comment]
image
image
It looks like there is a breakpoint issue, it looks like the mobile menu view is being applied to some of the larger screen resolutions.

**Comment by evandrosaturnino** [comment]
@benlongstaff appreciate the review, fixed the breakpoints issue for a smoother and better experience. 
commit: https://github.com/Threshold-USD/dev/pull/6/commits/2e47cb5d3ede1c992d149463cc9ed9453065210a
live version: https://thusd.on.fleek.co/#/
result:
https://user-images.githubusercontent.com/60587527/160671836-8c3b486a-49c0-463a-bcb6-53298f135ef5.mp4

**Comment by benlongstaff** [comment]
image
when the menu slides out on the right it partially cuts off the hamburger menu.

Should the Documentation, Discord and Github links be at the bottom to match the menu layout when the screen is maximised?

**Comment by evandrosaturnino** [comment]
> when the menu slides out on the right it partially cuts off the hamburger menu.
> 
> Should the Documentation, Discord and Github links be at the bottom to match the menu layout when the screen is maximised?

@benlongstaff thanks for the review, fixed the margin issue, as well the small adjustment on the icons matching the full width navigation bar: https://github.com/Threshold-USD/dev/pull/6/commits/813552f4b3b94369e7e712683173a08d904923d5

**Pull request merged**
